Repository kategengler/ember-cli-browserstack, pull requests merged in 2019-10, with the labels that each got.

#11 Add --project option support to browser launcher, make help work without ENV variables
  lib/tasks/launch-browserstack-browser.js
  lib/utils/build-name-from-env.js
  testem.js
Labels: enhancement

#23 Update outdated deps
  package.json
  yarn.lock
Labels: internal

#24 Use javascript so all browserstack launchers are used in CI without
  testem.js
Labels: internal

#26 Move ember-cli-htmlbars to devDep
  package.json
Labels: bug
